services:
  - type: web
    name: moto-income-backend
    env: node
    region: oregon
    root: backend
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_ADMIN_PASSWORD
        value: Spiro@2026
